###################################################
# +---------------------------------------------+ #
# |             Database Connection             | #
# +---------------------------------------------+ #
###################################################

# CAUTION! Developer mode will drop all database tables on startup. DO NOT USE IN PRODUCTION.  
developer-mode: true

# Database connection settings.
mysql:
  host: localhost
  port: 3306
  username: unitedwar
  password: unitedwar
  database: unitedwar

###################################################
# +---------------------------------------------+ #
# |                War Scheduler                | #
# +---------------------------------------------+ #
###################################################

warscheduler:
  check-interval: 15 # in seconds

###################################################
# +---------------------------------------------+ #
# |                 Mobilisation                | #
# +---------------------------------------------+ #
###################################################

# Town and Nation mobilisation settings

mobilisation:
  # How much mobilisation grows per Towny day if not peaceful.
  daily-growth: 1
  # How much mobilisation decays per Towny day if peaceful.
  daily-decay: 1
  # Minimum amount of mobilisation needed to declare a war.
  min-to-declare: 60
  # How much mobilisation decreases when a war is declared.
  cost-to-declare: 20
  # How much mobilisation costs to toggle peaceful.
  cost-to-toggle-peaceful: 1

###################################################
# +---------------------------------------------+ #
# |                 War Settings                | #
# +---------------------------------------------+ #
###################################################

wars-settings:

  default:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
    attacker-warchest-contribution: 0.1 # in percentage of town balance
    defender-warchest-contribution: 0.1
    attacker-score-cap: 500
    defender-score-cap: 500
    additional-bonus-claims: 20

  town-town:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
    attacker-warchest-contribution: 0.1
    defender-warchest-contribution: 0.1
    attacker-score-cap: 500
    defender-score-cap: 500
    additional-bonus-claims: 20

  town-nation:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
    attacker-warchest-contribution: 0.1
    defender-warchest-contribution: 0.1
    attacker-score-cap: 500
    defender-score-cap: 500
    additional-bonus-claims: 20

  nation-nation:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
    attacker-warchest-contribution: 0.1
    defender-warchest-contribution: 0.1
    attacker-score-cap: 500
    defender-score-cap: 500
    additional-bonus-claims: 20

  nation-town:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
    attacker-warchest-contribution: 0.1
    defender-warchest-contribution: 0.1
    attacker-score-cap: 500
    defender-score-cap: 500
    additional-bonus-claims: 20

###################################################
# +---------------------------------------------+ #
# |               Score settings                | #
# +---------------------------------------------+ #
###################################################

default-rewards:
  pvp-kill: 10
  pvp-leader-kill: 50
  siege-chunk-capture: 10
  siege-fortress-capture: 100
  siege-home-capture: 50

###################################################
# +---------------------------------------------+ #
# |               Siege settings                | #
# +---------------------------------------------+ #
###################################################

siege-settings:
  # If true, the health decay and restoration is applied per player in the majority:
  # 5 attackers vs. 2 defenders = 3 player majority for attackers = 3 * health decay rate per war tick
  # If false, the health decay and restoration only apply once per team in the majority
  use-superiority-multiplier: true;
  # The starting HP of chunks at the beginning of a war (relative to max health)
  health-start-percentage: 1.0
  # The amount of HP a chunk loses when the attackers are in a majority
  health-decay-rate: 1
  # The amount of HP a chunk heals when the defenders are in a majority
  health-restore-rate: 1
  # Initial max health points for chunk types
  town-chunk-health: 10
  home-chunk-health: 50
  fortress-chunk-health: 100

  grief-zone-settings:
    camp:
      radius: 0
      war-start-snapshot: false
      war-end-restore: true
      griefing-on-perms: "residentbuild,residentdestroy,residentswitch,residentitemuse,outsiderbuild,outsiderdestroy,nationbuild,nationdestroy,nationswitch,nationitemuse,allybuild,allydestroy,allyswitch,allyitemuse,pvp,fire,explosion"
      griefing-off-perms: "residentbuild,residentdestroy,residentswitch,residentitemuse,nationswitch,nationitemuse,allyswitch,allyitemuse"
    fortress:
      radius: 2
      war-start-snapshot: true
      war-end-restore: true
      griefing-on-perms: "residentbuild,residentdestroy,residentswitch,residentitemuse,outsiderbuild,outsiderdestroy,nationbuild,nationdestroy,nationswitch,nationitemuse,allybuild,allydestroy,allyswitch,allyitemuse,pvp,fire,explosion"
      griefing-off-perms: "residentbuild,residentdestroy,residentswitch,residentitemuse,nationswitch,nationitemuse,allyswitch,allyitemuse"

###################################################
# +---------------------------------------------+ #
# |                  War Events                 | #
# +---------------------------------------------+ #
###################################################

war-events:
  # Chance for a random event to happen every hour
  event-warmup-time: 30 # in seconds
  # 0.0 is disabled and 1.0 is guaranteed.
  random-event-chance: 0.0
  event-schedule:
    - "00:00"
  pick-table:
    "SAMPLE": 1

###################################################
# +---------------------------------------------+ #
# |                 Warzone PVP                 | #
# +---------------------------------------------+ #
###################################################

# Special rules for pvp inside of war zones (town in an active war). 
# These only apply to players participating in an active war.

warzone-pvp:
  disable-elytra: true
  disable-tp: false
  disable-pw: false
  cooldowns:
    projectiles:
      ENDER_PEARL: 5 # in seconds
      WIND_CHARGE: 5 # in seconds

###################################################
# +---------------------------------------------+ #
# |                  Messages                   | #
# +---------------------------------------------+ #
###################################################

messages:
  # Plugin prefix before every system message.
  prefix: "§c§lU§f§lL §7§lWar §8§l» "
  reload: "§2Plugin reloaded."
  invalid-command: "§cInvalid command usage."
  no-permission: '§2You don''t have permission to perform this command.'
  # {0} is the relevant town or nation name.
  town-nation-not-found: "§2No town or nation found named §e§l{0}"
  # {0} is the attempted input.
  not-a-number: "§e§l{0} §2is not a number."
  # {0} is the player username.
  player-not-found: "§e§l{0} is not a recognised username or not online."
  info-not-in-war: "§cYou are not in a war!"

  # +---------------------------------------------+ #
  # |               War Messages                  | #
  # +---------------------------------------------+ #

  war-started: "§fThe war §e§o{war-name} §7§rhas started! Get ready to fight - war point scoring is now active!"
  war-declared:
    - "§c§m+|✦       §r§c§l[§f§l WAR DECLARED §c§l]§c§m       |✦+"
    - "§f§c§o{war-name}"
    - "§7{war-description}"
    - "Attacker: {attacker} {attacker-nation} | Defender: {defender} {defender-nation}"
    - "§f§lWar Goal: §r{war-goal} | §lWar Chest: §r{war-chest-money}G / {war-chest-claims}"
    - "{attacker-ally-info} {defender-ally-info}"
    - "§f§l{timer-info}"
    - "§c§m+|✦                  +✦+                  |✦+"
  war-info: 
    - "§c§m+|✦       §r§c§l[§f§l {war-name} ({war-active}) §c§l]§c§m       |✦+"
    - "§7{war-description}"
    - "§f§lAttacker: §r{attacker} | §lScore: §r{attacker-score} / {attacker-score-cap}"
    - "§f§lDefender: §r{defender} | §lScore: §r{defender-score} / {defender-score-cap}"
    - "§f§lWar Goal: §r{war-goal} | §lWar Chest: §r{war-chest-money}G / {war-chest-claims}"
    - "{attacker-ally-info} {defender-ally-info}"
    - "§f§l{timer-info}"
    - "§c§m+|✦                  +✦+                  |✦+"
  war-ended: 
    - "§c§m+|✦       §r§c§l[§f§l {war-name} (ENDED)§c§l]§c§m       |✦+"
    - "§fThe war has ended with the following result:"
    - "§f§o{war-result}"
    - "§f§lAttacker: §r{attacker} | §lFinal score: §r{attacker-score} / {attacker-score-cap}"
    - "§f§lDefender: §r{defender} | §lFinal score: §r{defender-score} / {defender-score-cap}"
    - "§f§lWar Goal: §r{war-goal} | §lWar Chest: §r{war-chest-money}G / {war-chest-claims}"
    - "§c§m+|✦                  +✦+                  |✦+"

  # +---------------------------------------------+ #
  # |                War Events                   | #
  # +---------------------------------------------+ #

  event-info-scheduled: 
    - "§c§m+|✦       §r§c§l[§f§l {event-name} §c§l]§c§m       |✦+"
    - "§7A new war event will will begin soon! It will have the following effects:"
    - "§f{event-description}"
    - "§7The event will start in §e{event-relative-start} §7and last for §e{event-duration}§7."
    - "§c§m+|✦                  +✦+                  |✦+"
  event-info-active: 
    - "§c§m+|✦       §r§c§l[§f§l {event-name} §c§l]§c§m       |✦+"
    - "§f{event-description}"
    - "§7This event will end in §e{event-remaining-duration}."
    - "§c§m+|✦                  +✦+                  |✦+"
  event-info-ended:
    - "§c§m+|✦       §r§c§l[§f§l {event-name} §c§l]§c§m       |✦+"
    - "§f{event-description}"
    - "§7This event has now ended and all effects have been removed"
    - "§c§m+|✦                  +✦+                  |✦+"

  # +---------------------------------------------+ #
  # |               Mobilisation                  | #
  # +---------------------------------------------+ #

  mobilisation-usage: "§2Usage: §7/wa mobilisation [Town | Nation] set [0-100]"
  mobilisation-number-invalid: "§2Mobilisation must be set between 0-100."
  # {0} is the town or nation name.
  # {1} is the mobilisation amount.
  mobilisation-set:  "§e§l{0} §2mobilisation set to §e§l{1}"
  # {0} is the town or nation name.
  mobilisation-delete: "§e§l{0} §2mobilisation deleted."
  # {0} is the set cost to toggle.
  mobilisation-cost: "§bYou paid {0}% of your mobilisation to toggle peacefulness."
  # {0} is the town name.
  # Formatted to look like a towny system notification, editable to have it match if changed.
  mobilisation-notification-gain: "§6[{0}] §bBecause of non-neutral status, {0} has gained some mobilisation progress."
  mobilisation-notification-lose: "§6[{0}] §bBecause of neutral status, {0} has lost some mobilisation progress."


  # +---------------------------------------------+ #
  # |                  Scores                     | #
  # +---------------------------------------------+ #

  score-message: "§7You scored §f§l{score} points §7§rfor: §e{action}"
  score-capture-attacker: "§7Your team received §f§l{reward} points §7§rfor capturing a chunk in an enemy town!"
  score-capture-home-attacker: "§7Your team received §f§l{reward} points §7§rfor bringing down an enemy home chunk!"
  score-capture-fortress-attacker: "§7Your team received §f§l{reward} points §7§rfor capturing a chunk in an enemy town!"


  # +---------------------------------------------+ #
  # |                 War Lives                   | #
  # +---------------------------------------------+ #

  warlives-usage:
    # TURN INTO LIST
    - "§cInvalid command, try: §7/wa warlives [Player Name] set [Int] or /wa warlives [Player Name] delete"
  # {0} is the player username.
  warlives-delete: "§e§l{0} §2war lives removed from §e§l{2}"
  # {0} is the town or nation name.
  # {1} is the war lives amount.
  # {2} is the war name.
  warlives-set: "§e§l{0} §2war lives set to §e§l{1} §2in §e§l{2}§2."
  # {0} is the player username.
  # {1} is the war lives amount.
  # {2} is the war name.
  warlives-get: "§e§l{0} §7has §e§l{1} §2lives in §e§l{2}§2."
  # {0} is the amount of lives remaining.
  # {1} is the name of the war.
  warlives-lost: "§cYou died and lost a war life! You have §e§l{0} §cremaining in §e§l{1}§c."
  # {0} is the name of the war.
  warlives-final: "§cYou died and lost your final war life! You have been removed from §e§l{0}§c."
  warlives-gone: "§cYou died but have already lost your final war life!"