# ------------------------------------------
# Database connection settings
# ------------------------------------------

# CAUTION! Developer mode will drop all database tables on startup. DO NOT USE IN PRODUCTION.  
developer-mode: true

# Database connection settings
mysql:
  host: localhost
  port: 3306
  username: unitedwar
  password: unitedwar
  database: unitedwar

# ------------------------------------------
# War scheduler settings
# ------------------------------------------

warscheduler:
  check-interval: 15 # in seconds

###################################################
# +---------------------------------------------+ #
# |                 Mobilisation                | #
# +---------------------------------------------+ #
###################################################

# Town and Nation mobilisation settings

mobilisation:
  # How much mobilisation grows per Towny day if not peaceful.
  daily-growth: 1
  # How much mobilisation decays per Towny day if peaceful.
  daily-decay: 1
  # Minimum amount of mobilisation needed to declare a war.
  min-to-declare: 60
  # How much mobilisation decreases when a war is declared.
  cost-to-declare: 20
  # How much mobilisation costs to toggle peaceful.
  cost-to-toggle-peaceful: 1

# ------------------------------------------
# War events settings
# ------------------------------------------

war-events:
  # Chance for a random event to happen every hour
  event-warmup-time: 30 # in seconds
  random-event-chance: 0.5
  event-schedule:
  - "00:00"
  - "00:05"
  - "00:10"
  - "00:15"
  - "00:20"
  - "00:25"
  - "00:30"
  - "00:35"
  - "00:40"
  - "00:45"
  - "00:50"
  - "00:55"
  - "01:00"
  - "01:05"
  - "01:10"
  - "01:15"
  - "01:20"
  - "01:25"
  - "01:30"
  - "01:35"
  - "01:40"
  - "01:45"
  - "01:50"
  - "01:55"
  - "02:00"
  - "02:05"
  - "02:10"
  - "02:15"
  - "02:20"
  - "02:25"
  - "02:30"
  - "02:35"
  - "02:40"
  - "02:45"
  - "02:50"
  - "02:55"
  - "03:00"
  - "03:05"
  - "03:10"
  - "03:15"
  - "03:20"
  - "03:25"
  - "03:30"
  - "03:35"
  - "03:40"
  - "03:45"
  - "03:50"
  - "03:55"
  - "04:00"
  - "04:05"
  - "04:10"
  - "04:15"
  - "04:20"
  - "04:25"
  - "04:30"
  - "04:35"
  - "04:40"
  - "04:45"
  - "04:50"
  - "04:55"
  - "05:00"
  - "05:05"
  - "05:10"
  - "05:15"
  - "05:20"
  - "05:25"
  - "05:30"
  - "05:35"
  - "05:40"
  - "05:45"
  - "05:50"
  - "05:55"
  - "06:00"
  - "06:05"
  - "06:10"
  - "06:15"
  - "06:20"
  - "06:25"
  - "06:30"
  - "06:35"
  - "06:40"
  - "06:45"
  - "06:50"
  - "06:55"
  - "07:00"
  - "07:05"
  - "07:10"
  - "07:15"
  - "07:20"
  - "07:25"
  - "07:30"
  - "07:35"
  - "07:40"
  - "07:45"
  - "07:50"
  - "07:55"
  - "08:00"
  - "08:05"
  - "08:10"
  - "08:15"
  - "08:20"
  - "08:25"
  - "08:30"
  - "08:35"
  - "08:40"
  - "08:45"
  - "08:50"
  - "08:55"
  - "09:00"
  - "09:05"
  - "09:10"
  - "09:15"
  - "09:20"
  - "09:25"
  - "09:30"
  - "09:35"
  - "09:40"
  - "09:45"
  - "09:50"
  - "09:55"
  - "10:00"
  - "10:05"
  - "10:10"
  - "10:15"
  - "10:20"
  - "10:25"
  - "10:30"
  - "10:35"
  - "10:40"
  - "10:45"
  - "10:50"
  - "10:55"
  - "11:00"
  - "11:05"
  - "11:10"
  - "11:15"
  - "11:20"
  - "11:25"
  - "11:30"
  - "11:35"
  - "11:40"
  - "11:45"
  - "11:50"
  - "11:55"
  - "12:00"
  - "12:05"
  - "12:10"
  - "12:15"
  - "12:20"
  - "12:25"
  - "12:30"
  - "12:35"
  - "12:40"
  - "12:45"
  - "12:50"
  - "12:55"
  - "13:00"
  - "13:05"
  - "13:10"
  - "13:15"
  - "13:20"
  - "13:25"
  - "13:30"
  - "13:35"
  - "13:40"
  - "13:45"
  - "13:50"
  - "13:55"
  - "14:00"
  - "14:05"
  - "14:10"
  - "14:15"
  - "14:20"
  - "14:25"
  - "14:30"
  - "14:35"
  - "14:40"
  - "14:45"
  - "14:50"
  - "14:55"
  - "15:00"
  - "15:05"
  - "15:10"
  - "15:15"
  - "15:20"
  - "15:25"
  - "15:30"
  - "15:35"
  - "15:40"
  - "15:45"
  - "15:50"
  - "15:55"
  - "16:00"
  - "16:05"
  - "16:10"
  - "16:15"
  - "16:20"
  - "16:25"
  - "16:30"
  - "16:35"
  - "16:40"
  - "16:45"
  - "16:50"
  - "16:55"
  - "17:00"
  - "17:05"
  - "17:10"
  - "17:15"
  - "17:20"
  - "17:25"
  - "17:30"
  - "17:35"
  - "17:40"
  - "17:45"
  - "17:50"
  - "17:55"
  - "18:00"
  - "18:05"
  - "18:10"
  - "18:15"
  - "18:20"
  - "18:25"
  - "18:30"
  - "18:35"
  - "18:40"
  - "18:45"
  - "18:50"
  - "18:55"
  - "19:00"
  - "19:05"
  - "19:10"
  - "19:15"
  - "19:20"
  - "19:25"
  - "19:30"
  - "19:35"
  - "19:40"
  - "19:45"
  - "19:50"
  - "19:55"
  - "20:00"
  - "20:05"
  - "20:10"
  - "20:15"
  - "20:20"
  - "20:25"
  - "20:30"
  - "20:35"
  - "20:40"
  - "20:45"
  - "20:50"
  - "20:55"
  - "21:00"
  - "21:05"
  - "21:10"
  - "21:15"
  - "21:20"
  - "21:25"
  - "21:30"
  - "21:35"
  - "21:40"
  - "21:45"
  - "21:50"
  - "21:55"
  - "22:00"
  - "22:05"
  - "22:10"
  - "22:15"
  - "22:20"
  - "22:25"
  - "22:30"
  - "22:35"
  - "22:40"
  - "22:45"
  - "22:50"
  - "22:55"
  - "23:00"
  - "23:05"
  - "23:10"
  - "23:15"
  - "23:20"
  - "23:25"
  - "23:30"
  - "23:35"
  - "23:40"
  - "23:45"
  - "23:50"
  - "23:55"
  pick-table:
    "SAMPLE1": 1
    "SAMPLE2": 1
    "SAMPLE3": 1
    "SAMPLE4": 1

# ------------------------------------------
# War settings
# ------------------------------------------

wars-settings:
  default:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
    attacker-warchest-contibution: 0.1 # in percentage of town balance
    defender-warchest-contibution: 0.1 
    attacker-score-cap: 500
    defender-score-cap: 500
  town-town:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
    attacker-warchest-contibution: 0.1 
    defender-warchest-contibution: 0.1
    attacker-score-cap: 500
    defender-score-cap: 500
  town-nation:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
    attacker-warchest-contibution: 0.1 
    defender-warchest-contibution: 0.1
    attacker-score-cap: 500
    defender-score-cap: 500
  nation-nation:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
    attacker-warchest-contibution: 0.1
    defender-warchest-contibution: 0.1 
    attacker-score-cap: 500
    defender-score-cap: 500
  nation-town:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
    attacker-warchest-contibution: 0.1 
    defender-warchest-contibution: 0.1
    attacker-score-cap: 500
    defender-score-cap: 500

###################################################
# +---------------------------------------------+ #
# |                  Messages                   | #
# +---------------------------------------------+ #
###################################################

messages:
  # Plugin prefix before every system message.
  prefix: "§c§lU§f§lL §7§lWar §8§l» "
  reload: "§2Plugin reloaded."
  invalid-command: "§cInvalid command usage."
  no-permission: '§2You don''t have permission to perform this command.'
  usage-mobilisation: "§2Usage: §7/wa mobilisation [Town | Nation] set [0-100]"
  # {0} is the relevant town or nation name.
  town-nation-not-found: "§2No town or nation found named §e§l{0}"
  # {0} is the attempted input.
  not-a-number: "§e§l{0} §2is not a number."
  # {0} is the player username.
  player-not-found: "§e§l{0} is not a recognised username or not online."
  invalid-mobilisation-number: "§2Mobilisation must be set between 0-100."
  # {0} is the town or nation name.
  # {1} is the mobilisation amount.
  mobilisation-set:  "§e§l{0} §2mobilisation set to §e§l{1}"
  # {0} is the town or nation name.
  mobilisation-delete: "§e§l{0} §2mobilisation deleted."
  # {0} is the set cost to toggle.
  mobilisation-cost: "§bYou paid {0}% of your mobilisation to toggle peacefulness."
  # {0} is the town name.
  # Formatted to look like a towny system notification, editable to have it match if changed.
  mobilisation-notification-gain: "§6[{0}] §bBecause of non-neutral status, {0} has gained some mobilisation progress."
  mobilisation-notification-lose: "§6[{0}] §bBecause of neutral status, {0} has lost some mobilisation progress."
  war-started: "§fThe war §e§o{war-name} §7§rhas started! Get ready to fight - war point scoring is now active!"
  war-declared:
    - "§c§m+|✦       §r§c§l[§f§l WAR DECLARED §c§l]§c§m       |✦+"
    - "§f§c§o{war-name}"
    - "§7{war-description}"
    - "Attacker: {attacker} {attacker-nation} | Defender: {defender} {defender-nation}"
    - "§f§lWar Goal: §r{war-goal} | War Chest: §r{war-chest}G"
    - "{attacker-ally-info} {defender-ally-info}"
    - "§f§l{timer-info}"
    - "§c§m+|✦                  +✦+                  |✦+"
  war-info: 
    - "§c§m+|✦       §r§c§l[§f§l {war-name} ({war-active}) §c§l]§c§m       |✦+"
    - "§7{war-description}"
    - "§f§lAttacker: §r{attacker} | §lScore: §r{attacker-score} / {attacker-score-cap}"
    - "§f§lDefender: §r{defender} | §lScore: §r{defender-score} / {defender-score-cap}"
    - "§f§lWar Goal: §r{war-goal} | War Chest: §r{war-chest}G"
    - "{attacker-ally-info} {defender-ally-info}"
    - "§f§l{timer-info}"
    - "§c§m+|✦                  +✦+                  |✦+"
  war-ended: 
    - "§c§m+|✦       §r§c§l[§f§l {war-name} (ENDED)§c§l]§c§m       |✦+"
    - "§fThe war has ended with the following result:"
    - "§f§o{war-result}"
    - "§f§lAttacker: §r{attacker} | §lFinal score: §r{attacker-score} / {attacker-score-cap}"
    - "§f§lDefender: §r{defender} | §lFinal score: §r{defender-score} / {defender-score-cap}"
    - "§f§lWar Goal: §r{war-goal} | War Chest: §r{war-chest}G"
    - "§c§m+|✦                  +✦+                  |✦+"
  info-not-in-war: "§cYou are not in a war!"
  event-info-scheduled: 
    - "§c§m+|✦       §r§c§l[§f§l {event-name} §c§l]§c§m       |✦+"
    - "§7A new war event will will begin soon! It will have the following effects:"
    - "§f{event-description}"
    - "§7The event will start in §e{event-relative-start} §7and last for §e{event-duration}§7."
    - "§c§m+|✦                  +✦+                  |✦+"
  event-info-active: 
    - "§c§m+|✦       §r§c§l[§f§l {event-name} §c§l]§c§m       |✦+"
    - "§f{event-description}"
    - "§7This event will end in §e{event-remaining-duration}."
    - "§c§m+|✦                  +✦+                  |✦+"
  event-info-ended:
    - "§c§m+|✦       §r§c§l[§f§l {event-name} §c§l]§c§m       |✦+"
    - "§f{event-description}"
    - "§7This event has now ended and all effects have been removed"
    - "§c§m+|✦                  +✦+                  |✦+"
# +---------------------------------------------+
# |                 War Lives                   |
# +---------------------------------------------+
  warlives-usage:
    # TURN INTO LIST
    - "§cInvalid command, try: §7/wa warlives [Player Name] set [Int] or /wa warlives [Player Name] delete"
  # {0} is the player username.
  warlives-delete: "§e§l{0} §2war lives deleted."
  # {0} is the town or nation name.
  # {1} is the mobilisation amount.
  warlives-set:  "§e§l{0} §2war lives set to §e§l{1}"