# ------------------------------------------
# Database connection settings
# ------------------------------------------

# CAUTION! Developer mode will drop all database tables on startup. DO NOT USE IN PRODUCTION.  
developer-mode: true

# Database connection settings
mysql:
  host: localhost
  port: 3306
  username: unitedwar
  password: unitedwar
  database: unitedwar

# ------------------------------------------
# War scheduler settings
# ------------------------------------------

warscheduler:
  check-interval: 15 # in seconds

# ------------------------------------------
# War events settings
# ------------------------------------------

war-events:
  # Chance for a random event to happen every hour
  random-event-chance: 0.5
  pick-table:
    "SAMPLE1": 0.6
    "SAMPLE2": 0.4
    "SAMPLE3": 0.2
    "SAMPLE4": 0.1

# ------------------------------------------
# War settings
# ------------------------------------------

wars-settings:
  default:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
  town-town:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
  town-nation:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
  nation-nation:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds
  nation-town:
    warmup-time: 60 # in seconds
    duration: 3600 # in seconds