name: UnitedWar
version: '${project.version}'
main: org.unitedlands.UnitedWar
api-version: 1.21
description: A custom war plugin for United Lands.
authors: [ Litning11, Theriel_]
depend: [ Towny ]
commands:
  wardebug:
     description: Debugging commands.
     aliases: [wd]
  waradmin:
     description: Admin commands for war.
     aliases: [wa]