name: UnitedWar
version: 0.1
main: org.unitedlands.UnitedWar
api-version: 1.18
description: A custom war plugn for UnitedLands.
author: Theriel_
commands:
  wardebug:
     description: Debugging commands.
     permission: united.war.admin
     aliases: [wd]
  waradmin:
     description: War admin commands.
     permission: united.war.admin
     aliases: [wa]
  